[package]
name = "blobtorrent"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
dirs.workspace = true
serde.workspace = true
serde_json.workspace = true
url.workspace = true
simple-dns.workspace = true
z32.workspace = true
anyhow.workspace = true
clap.workspace = true
irpc.workspace = true
irpc-iroh.workspace = true
rand.workspace = true
hex.workspace = true
tokio.workspace = true
iroh.workspace = true
iroh-blobs.workspace = true
n0-future.workspace = true
walkdir.workspace = true
blake3.workspace = true
iroh-mainline-endpoint-discovery.workspace = true
iroh-local-gateway.workspace = true
n0-mainline.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
blobtorrent-proto = { workspace = true, features = ["client"] }

[dev-dependencies]
bao-tree = "0.16"
tempfile.workspace = true
